channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - requests
  - numba
  - numpy
  - pandas
  - scipy
  - matplotlib
  - ipywidgets
  - rise
  - pip:
    - jupyter-contrib-nbextensions
